apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: hexboard
  name: hexboard
  namespace: hexboard
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hexboard
    deploymentconfig: hexboard
  sessionAffinity: None
  type: ClusterIP
