apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hexboard
  name: hexboard
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: hexboard
        deploymentconfig: hexboard
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN
              value: >-
                ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpvWlhoaWIyRnlaQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUprWldaaGRXeDBMWFJ2YTJWdUxYUnVkSFIySWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1SbFptRjFiSFFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUpsWXpKbFptVTNNUzAyT1dNMUxURXhaVGd0T0RKa1l5MHdZVFU0WVdNeFpqQmtaRFlpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNmFHVjRZbTloY21RNlpHVm1ZWFZzZENKOS5VSVp4VTBWSS1Td3ZlTzVzWUFMeW4tN2N5MDU2YS1uYWVmYktUWUQ2bzI5Q00xZzhFVjduaDJXYjZoU2piaWx2UWJXNWw5RENvSy1SbEQxaWFqZTdYQThzTldWSHNuT29sc25rTWNSVU9WWHVabmlZVEFsWlNUd2ZmMXFNbHlUc0R5TTdCWHE0X0RjMGtqOTVDc21ZbXVVRm1nbDJNTGpjdVZzaWVZOUNxZjBxMWh5Y0VOZkhmUG5QQ1VnV0FsY0xKOGRiTE0tRDMwcGxzSTFpUW44OXRjeDZRaTBla0JxZGFndDJSc3k1ZFJjc3d3M1dvcjgtc1RPYnhQZ2lvV2Y4V0hISXA4OGpRZTNHZExaNkVXT1lDWHhiODJQNU5DMjJNci1nb0ZjcTN5WGlPUnRNTUE1TW5OZ0lhdmF0X0FuaE1TVXZBSHR0OHpMbUFxeTREcVE3YVZGREtycjlFRmI2SlZReUtzUDFYRGJMX2taOGpqby1Ta3A1MkloRFFoUzRCTkJ1blJyN1dTbE9USUJiOHlhZFZVRElKVVc5V2xEcW9PUWM3RmpjeEtHc1hqdWtwZzV1aXdMZ3NTbDdqSkh3Nzh4NThFLUJ6YjZxajVxYUsxQjRzT0c5eWxQVEUwQTE4elZVUENqZWpaQ2U0UkpQNnB4SGtvOG53ekxDQUwxWER6Y3JrN3FHQklOblRTb2N4MWNKZllTQk5fa3RsSUVtZWZRc1RNNzdKX0FGNElzTEc0MV9pWWpVTW8tRkpaNzEzRmR6QXVBUUNkM3lGckNnOFVnMkpiY0dTb2xLVktVdXpYWGlKYzBVQm1ST1VYZTNIa3FTREdVa1ZseVVSTVBERlRTZ1Q4cnhiZnc2amNjOWV6dW9COU1pUFMzNGp6aXBvRF9FQTlQN0Jvcw==
            - name: HEXBOARD_SIZE
              value: xsmall
            - name: WINNER_COUNT
              value: '2'
            - name: ADMIN_TOKEN
              value: hexboard!
          image: ghoelzer2azure/hexboard:latest
          imagePullPolicy: IfNotPresent
          name: hexboard
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

