apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: sketchpod
  name: sketchpod
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sketchpod
    deploymentconfig: sketchpod
  sessionAffinity: None
  type: ClusterIP
